### ISSUE TITLE
QVNCClientWidget not working 

### ISSUE THREAD

**Issue by Martinfx** [tomilov/qvncclient#2]
Hi,
I have a problem with show content with bhyve on  FreeBSD 
I tried connect without problem but he shows only red screen
```
Security Handshake
Server Answer :  "RFB 003.008\n"
Connection successful
Security Result  "\x00\x00\x00\x00"
ui->vncView->isConnectedToServer() true
```
from FreeBSD is 
```
rfb unknown cli-code 1!


```

**Comment by tomilov** [comment]
This is a fork. It seems that original repo is ceased to exists.
